import React, {useEffect,useRef,useState} from 'react';
import {Activity,Box,FolderOpen,Play,Square,Download,Upload,Terminal,ChevronDown,X,RefreshCw} from 'lucide-react';
import {api,authenticate} from './api';
import {assignGroups,validateImport,hydrateConfig,launchAllowed} from './workspace';
import Graph from './Graph';
import './style.css';
export const bytes = n => n == null ? 'unavailable' : n >= 1073741824 ? `${(n/1073741824).toFixed(2)} GiB` : `${(n/1048576).toFixed(0)} MiB`;
export default function App(){
 const [config,setConfig]=useState(null),[model,setModel]=useState(null),[caps,setCaps]=useState(null),[plan,setPlan]=useState(null),[runtime,setRuntime]=useState(null);
 const [error,setError]=useState(''),[busy,setBusy]=useState('Connecting'),[dirty,setDirty]=useState(false),[drawer,setDrawer]=useState(false),[tab,setTab]=useState('command'),[selected,setSelected]=useState([]),[filter,setFilter]=useState('');
 const current=useRef(config),version=useRef(0),attemptedPlan=useRef(-1),file=useRef(null); current.current=config;
 const receive=data=>{if(data.config){current.current=hydrateConfig(data.config);setConfig(current.current);} if('model'in data)setModel(data.model);if(data.capabilities)setCaps(data.capabilities);if('plan'in data)setPlan(data.plan);if(data.runtime)setRuntime(data.runtime);};
 useEffect(()=>{let alive=true; authenticate().then(()=>api('/state')).then(data=>{if(alive)receive(data)}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setBusy(''));return()=>{alive=false}},[]);
 useEffect(()=>{if(!config)return;let alive=true;const id=setInterval(()=>api('/runtime').then(r=>alive&&setRuntime(r)).catch(e=>alive&&setError(e.message)),2000);return()=>{alive=false;clearInterval(id)}},[!!config]);
 const change=next=>{version.current++;current.current=hydrateConfig(typeof next==='function'?next(current.current):next);setConfig(current.current);setDirty(true)};
 const run=async(label,fn)=>{setBusy(label);setError('');try{return await fn()}catch(e){setError(e.message)}finally{setBusy('')}};
 const replan=async(mode)=>{const v=version.current;attemptedPlan.current=v;const result=await api('/plan',{config:current.current,...(mode?{mode}:{})});if(v===version.current){setPlan(result);if(result.config)setConfig(hydrateConfig({...result.config,positions:current.current.positions,edges:current.current.edges}));setDirty(false)}return result;};
 useEffect(()=>{if(!dirty||!model||busy||attemptedPlan.current===version.current)return;const id=setTimeout(()=>run('Planning',()=>replan()),400);return()=>clearTimeout(id)},[config,dirty,model,busy]);
 const load=()=>run('Reading GGUF',async()=>{const v=++version.current;const result=await api('/model',{path:current.current.model_path,executable:current.current.executable});if(v!==version.current){setPlan(null);setError('Workspace changed while loading. Load the model again to validate your current settings.');return}receive(result);setDirty(false);setSelected([])});
 const assign=(ids,device)=>change(assignGroups(current.current,ids,device));
 const save=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(config,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='allocator-workspace.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const importFile=async(e)=>{const f=e.target.files[0];e.target.value='';if(!f)return;run('Validating workspace',async()=>{if(f.size>4*1024*1024)throw Error('Workspace exceeds 4 MiB.');const imported=validateImport(await f.text());const loaded=await api('/model',{path:imported.model_path,executable:imported.executable});const result=await api('/plan',{config:imported});version.current++;receive(loaded);setConfig(hydrateConfig({...result.config,positions:imported.positions,edges:imported.edges}));setPlan(result);setDirty(false);setSelected([])})};
 const status=dirty?'PENDING':plan?.status||'NO MODEL';
 return <div className="app"><header className="app-header"><div className="brand"><Box size={23}/><div>LLAMA<span>VISUAL ALLOCATOR</span></div><span className="local">LOCAL / ONLY</span></div><div className="connection"><i className={config?'dot online':'dot'}/>{busy||'Workspace ready'}<span className="muted"> / llama.cpp</span></div></header>
 <section className="commandbar" aria-label="Workspace commands"><div className="path-field"><label htmlFor="executable">EXECUTABLE</label><input id="executable" aria-label="Executable path" value={config?.executable||''} disabled={!config} placeholder="/path/to/llama-server" onChange={e=>change({...config,executable:e.target.value})}/><button title="Probe executable and devices" disabled={!config||!!busy} onClick={()=>run('Probing executable',async()=>{const v=++version.current;const result=await api('/probe',{executable:current.current.executable});if(v!==version.current){setPlan(null);setError('Workspace changed while probing. Probe again to refresh devices.');return}receive(result);setPlan(null);setDirty(true)})}><RefreshCw size={14}/></button></div><div className="path-field model-path"><label htmlFor="model-path">GGUF MODEL</label><input id="model-path" aria-label="Model path" value={config?.model_path||''} disabled={!config} placeholder="/path/to/model.gguf" onChange={e=>change({...config,model_path:e.target.value})}/><button aria-label="Load model" disabled={!config?.model_path||!!busy} onClick={load}><FolderOpen size={14}/>Load</button></div><div className="file-actions"><button title="Save workspace" aria-label="Save workspace" disabled={!config} onClick={save}><Download size={16}/></button><button title="Load workspace" aria-label="Load workspace" disabled={!config||!!busy} onClick={()=>file.current.click()}><Upload size={16}/></button><input ref={file} type="file" accept=".json,application/json" hidden onChange={importFile}/></div></section>
 <div className="allocationbar"><div className="workspace-title"><span className="eyebrow">01 / ALLOCATION GRAPH</span><strong>{model?.name||'Untitled workspace'}</strong></div><div className="allocation-actions"><button disabled={!model||!!busy} onClick={()=>run('Maximum fit',()=>replan('maximum'))}>Auto Maximum Fit</button><button disabled={!model||!!busy} onClick={()=>run('Balancing',()=>replan('balance'))}>Auto Balance</button><span className="divider"/><button className="primary" aria-label="Start server" disabled={!launchAllowed(plan,config)||dirty||!!busy||runtime?.running} onClick={()=>run('Starting',async()=>{setRuntime(await api('/start',{config}));setDrawer(true);setTab('logs')})}><Play size={14}/>Start</button><button aria-label="Stop server" disabled={!runtime?.running||!!busy} onClick={()=>run('Stopping',async()=>setRuntime(await api('/stop',{})))}><Square size={12}/>Stop</button></div></div>
 {error&&<div role="alert" className="error-banner">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={14}/></button></div>}
 <main className="workarea">{config?<Graph config={config} model={model} caps={caps} plan={plan} runtime={runtime} onChange={change} onAssign={assign} onError={setError} selected={selected} setSelected={setSelected} filter={filter}/>:<div className="boot-empty"><Box size={36}/><h2>{busy?'Connecting to local control plane':'Workspace is locked'}</h2><p>{busy?'Exchanging the launch token and reading live state.':'Open a fresh launch link from the local allocator process.'}</p><button onClick={()=>location.reload()}>Retry connection</button></div>}
 {config&&<aside className="inspector"><div className="inspector-heading"><span className="eyebrow">INSPECT</span><span className={'status '+status.replaceAll(' ','-').toLowerCase()}>{status}</span></div><h2>Allocation details</h2><p className="muted">{model?`${model.architecture||'GGUF'} · ${model.layer_count} layers · ${model.groups.length} groups`:'Load a GGUF to inspect its real architecture.'}</p><label className="field">Find a tensor group<input aria-label="Filter groups" placeholder="Layer, attention, expert…" value={filter} onChange={e=>setFilter(e.target.value)}/></label><div className="selection-summary"><b>{selected.length}</b> groups selected<button disabled={!selected.length} onClick={()=>setSelected([])}>Clear</button></div><label className="field">Place selection & lock<select aria-label="Place selected groups" value="" disabled={!selected.length||config.placement_mode==='layer'} onChange={e=>assign(selected,e.target.value)}><option value="">Choose device…</option>{(caps?.devices||[]).map(d=><option key={d.id} value={d.id} disabled={d.available===false||(!!d.alias_of&&d.id!=='MMAP')||d.supported===false||config.devices?.[d.id]?.enabled===false}>{d.id} · {d.name}</option>)}</select></label><button className="full" disabled={!selected.length} onClick={()=>change({...config,locked:config.locked.filter(id=>!selected.includes(id))})}>Unlock selection for auto allocation</button><div className="inspector-rule"/><h3>Budget policy</h3><NumberField label="Safety headroom / MiB" value={config.overhead_mib} onChange={v=>change({...config,overhead_mib:v})}/><NumberField label="Compute estimate / MiB" value={config.compute_mib} onChange={v=>change({...config,compute_mib:v})}/><label className="check"><input type="checkbox" checked={config.mmap} onChange={e=>change({...config,mmap:e.target.checked})}/>Memory-map model files</label><p className="hint">Mapped bytes are CPU-backed, not extra device capacity. Resident memory is budgeted against RAM.</p><div className="inspector-rule"/><h3>Validation & assumptions</h3>{!plan?<p className="hint">No plan yet. Nothing will launch until the local engine validates a model and its device routes.</p>:<><ul className="messages">{(plan.errors||[]).map((w,i)=><li className="danger" key={'e'+i}>{w}</li>)}{[...(plan.warnings||[]),...(caps?.warnings||[]),...(model?.warnings||[])].map((w,i)=><li key={'w'+i}>{w}</li>)}</ul><details><summary>{plan.assumptions?.length||0} estimation assumptions</summary><ul className="messages">{plan.assumptions?.map((w,i)=><li key={i}>{w}</li>)}</ul></details></>}</aside>}
 </main><section className="memory-strip" aria-label="Memory budgets"><div className="memory-label"><span className="eyebrow">MEMORY LEDGER</span><span className="hint">Estimated · not measured</span></div><div className="memory-devices">{plan?.memory?.length?plan.memory.map(m=><div className={'memory-cell '+deviceClass(m.id)} key={m.id}><div><b>{m.id}</b><span className={m.status==='OOM'?'danger':''}>{bytes(m.used_bytes)} <small>/ {bytes(m.cap_bytes)}</small></span></div><div className="memory-meter">{['weights','kv','compute','backend','draft','vision','overhead'].map((k,i)=><i key={k} title={`${k}: ${bytes(m[k])}`} style={{width:`${Math.max(0,Math.min(100,(m[k]||0)/(m.cap_bytes||1)*100))}%`,opacity:1-i*.11}}/>)}</div><div className="memory-sub"><span>{bytes(m.free_bytes)} free</span><span>{m.mapped_bytes?`${bytes(m.mapped_bytes)} mapped`:m.status}</span></div></div>):<p className="hint">Device budgets appear after a model is loaded and planned. No synthetic capacity.</p>}</div></section>
 <footer><span><i className={'dot '+(runtime?.running?'online':'')}/>{runtime?.running?`PID ${runtime.pid} · ${runtime.health||'starting'}`:'SERVER STOPPED'}</span><span className="footer-help">Drag group ports to devices · Shift-select groups · Scroll to zoom</span><button onClick={()=>setDrawer(!drawer)}><Terminal size={14}/>Runtime & command<ChevronDown size={13} style={{transform:drawer?'rotate(180deg)':undefined}}/></button></footer>
 {drawer&&<section className="runtime-drawer"><div className="drawer-header"><div>{['command','logs','metrics'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div><button aria-label="Close runtime drawer" onClick={()=>setDrawer(false)}><X size={16}/></button></div>{tab==='command'?<><p className="hint">Exact argv generated by the local engine. No shell execution.</p><pre>{plan?.command||'Load a model to generate a validated launch command.'}</pre></>:tab==='logs'?<pre role="log">{runtime?.logs?.join('\n')||'No runtime output. Start a validated plan to stream server logs.'}</pre>:<div className="metrics">{[['Process RSS',bytes(runtime?.rss_bytes)],['Prompt tokens/s',runtime?.prompt_tps],['Generation tokens/s',runtime?.generation_tps],['Draft acceptance',runtime?.acceptance],['Uptime / seconds',runtime?.uptime]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value??'unavailable'}</strong></div>)}<pre>{runtime?.gpu_process_bytes&&Object.keys(runtime.gpu_process_bytes).length?JSON.stringify(runtime.gpu_process_bytes,null,2):'Per-process GPU memory unavailable'}</pre></div>}</section>}
 </div>
}
export function deviceClass(id=''){return id.toUpperCase().includes('CUDA')?'cuda':id.toUpperCase().includes('VULKAN')?'vulkan':'ram'}
export function NumberField({label,value,onChange,min=0,max,step=1,optional=false,placeholder}){return <label className="field">{label}<input className="nodrag" type="number" aria-label={label} value={value??''} placeholder={placeholder} min={min} max={max} step={step} onChange={e=>{if(e.target.value!=='')onChange(Number(e.target.value));else if(optional)onChange(undefined)}}/></label>}
