import React,{useMemo,useState,useEffect} from 'react';
import {ReactFlow,Background,Controls,MiniMap,Handle,Position,useUpdateNodeInternals} from '@xyflow/react';
import {Box,Cpu,Layers,Lock,ChevronRight,Workflow,Server} from 'lucide-react';
import {bytes,deviceClass,NumberField} from './App';
import {connectGraph,hydrateConfig} from './workspace';
import {SplitNode,SamplingNode,VisionNode,FlagSupport,Toggle} from './FlagNodes';
import '@xyflow/react/dist/style.css';
const port=(type,id,style)=> <Handle type={type} position={type==='source'?Position.Right:Position.Left} id={id} style={style}/>;
function Heading({icon:Icon,title,tag}){return <div className="node-heading"><Icon size={16}/><b>{title}</b><span>{tag}</span></div>}
export function ModelNode({id,data}){
 const {model,config,selected,setSelected,filter}=data;const [expanded,setExpanded]=useState({});const update=useUpdateNodeInternals();
 const layers=useMemo(()=>{const result=new Map();for(const g of [...(model?.groups||[])].sort((a,b)=>(a.layer??-1)-(b.layer??-1))){const key=g.layer==null?'Global tensors':`Layer ${g.layer}`;if(!result.has(key))result.set(key,[]);result.get(key).push(g)}return [...result]},[model]);
 useEffect(()=>{update(id)},[expanded,filter,model,id,update]);
 const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
 return <section className="graph-node model-node"><Heading icon={Box} title="Model architecture" tag="GGUF"/>{!model?<div className="model-empty"><Layers size={32}/><h3>Your model, unpacked.</h3><p>Load a local GGUF above to reveal its layers, tensor groups, and actual weight sizes.</p><span>Weights stay on disk during inspection.</span></div>:<><div className="model-info"><strong>{model.name}</strong><div>{model.architecture} <span>· {model.layer_count} layers</span></div><b>{bytes(model.weight_bytes)}<small> TENSOR WEIGHTS</small></b></div><div className="model-tools nodrag"><span>{model.groups.length} groups</span><button onClick={()=>setExpanded(Object.fromEntries(layers.map(([k])=>[k,true])))}>Expand all</button><button onClick={()=>setExpanded({})}>Collapse</button></div><div className="layer-list nodrag nowheel">{layers.map(([name,groups])=>{const matching=groups.filter(g=>!filter||`${g.label} ${g.kind} ${name} ${g.tensor_names?.join(' ')}`.toLowerCase().includes(filter.toLowerCase()));if(!matching.length)return null;const open=expanded[name]||!!filter;return <div className="layer" key={name}><button className="layer-heading" onClick={()=>setExpanded({...expanded,[name]:!expanded[name]})}><ChevronRight size={12} style={{transform:open?'rotate(90deg)':undefined}}/><b>{name}</b><span>{groups.length} groups · {bytes(groups.reduce((s,g)=>s+g.nbytes,0))}</span></button>{open?matching.map(g=><div key={g.id} className={'group-row '+(selected.includes(g.id)?'group-selected':'')} draggable={config.placement_mode!=='layer'} onDragStart={e=>e.dataTransfer.setData('application/allocator-groups',JSON.stringify(selected.includes(g.id)?selected:[g.id]))}><input aria-label={`Select ${g.label}`} type="checkbox" checked={selected.includes(g.id)} onChange={()=>toggle(g.id)}/><div className="group-description"><span title={g.tensor_names?.join('\n')}>{g.label}</span><small>{g.kind} · {bytes(g.nbytes)}</small></div><span className={'group-device '+deviceClass(config.placements?.[g.id])}>{config.placements?.[g.id]||'unassigned'}</span>{config.locked?.includes(g.id)&&<Lock size={10}/>} {port('source',g.id)}</div>):<div className="collapsed-ports">{groups.map(g=><Handle key={g.id} type="source" position={Position.Right} id={g.id} style={{top:'50%',opacity:.35}}/>)}</div>}</div>})}</div><div className="node-foot">Select groups or drag a row onto a device.</div></>}{port('source','model-out',{top:49})}</section>
}
export function DeviceNode({data}){
 const {device:d,config,onChange,onAssign,memory:m}=data;const settings=config.devices?.[d.id]||{};const unavailable=d.available===false||d.supported===false||(!!d.alias_of&&d.id!=='MMAP');const update=patch=>onChange({...config,devices:{...config.devices,[d.id]:{...settings,...patch}}});
 return <section data-testid={'device-'+d.id} className={'graph-node device-node '+deviceClass(d.id)+(unavailable?' unavailable':'')} onDragOver={e=>{if(config.placement_mode!=='layer'&&!unavailable&&settings.enabled!==false)e.preventDefault()}} onDrop={e=>{e.preventDefault();if(config.placement_mode==='layer'||unavailable||settings.enabled===false)return;try{const ids=JSON.parse(e.dataTransfer.getData('application/allocator-groups'));if(Array.isArray(ids)&&ids.every(x=>typeof x==='string'))onAssign(ids,d.id)}catch{}}}>
 <Heading icon={Cpu} title={d.id} tag={unavailable?'UNAVAILABLE':d.kind||'MEMORY'}/>{!unavailable&&settings.enabled!==false&&port('target','allocation')}<div className="device-body nodrag"><strong>{d.name}</strong><p className="hint">{d.id==='MMAP'?'CPU-backed file mappings · not separate capacity':`${bytes(d.free_bytes)} available / ${bytes(d.total_bytes)} physical`}</p>{unavailable?<p className="danger">{d.alias_of?`Alias of ${d.alias_of}; not additional capacity.`:d.reason||'No verified tensor-buffer route.'}</p>:<><div className="device-budget"><NumberField label={`${d.id} cap / MiB`} value={settings.cap_mib} onChange={v=>update({cap_mib:v})}/><NumberField label={`${d.id} backend / MiB`} value={settings.backend_mib} onChange={v=>update({backend_mib:v})}/></div><label className="check"><input type="checkbox" checked={settings.enabled!==false} onChange={e=>update({enabled:e.target.checked})}/>Available for allocation</label></>}{m&&<div className="node-budget"><span>Projected resident</span><b>{bytes(m.used_bytes)}</b><div className="device-meter"><i style={{width:`${Math.min(100,Math.max(0,m.used_bytes/(m.cap_bytes||1)*100))}%`}}/></div><span className={m.status==='OOM'?'danger':''}>{m.status} · {bytes(m.free_bytes)} remaining</span></div>}</div></section>
}
export function ContextNode({data}){const {config,caps,onChange}=data;const update=(key,v)=>onChange({...config,context:{...config.context,[key]:v}});return <section className="graph-node context-node"><Heading icon={Layers} title="Context & KV cache" tag="CONFIG"/>{port('source','context')}<div className="node-form nodrag"><div className="form-grid">{[['Context tokens','size'],['Parallel slots','parallel'],['Batch','batch'],['Micro batch','ubatch']].map(([label,key])=><NumberField key={key} label={label} value={config.context[key]} min={1} onChange={v=>update(key,v)}/>)}{[['Key cache','k_type'],['Value cache','v_type']].map(([label,key])=><label className="field" key={key}>{label}<select value={config.context[key]} onChange={e=>update(key,e.target.value)}>{[...new Set([config.context[key],...(caps?.cache_types||[])])].map(v=><option key={v}>{v}</option>)}</select></label>)}</div><label className="field">Flash attention<select value={config.context.flash} onChange={e=>update('flash',e.target.value)}>{['auto','on','off'].map(v=><option key={v}>{v}</option>)}</select></label><FlagSupport caps={caps} flags={['--no-kv-offload']}><Toggle label="Offload KV cache to GPUs" value={config.context.kv_offload} onChange={v=>update('kv_offload',v)}/></FlagSupport><p className="hint">Off: KV stays in RAM. On: standard layer split can offload KV. Manual tensor mode still uses CPU KV (ngl=0); weight overrides do not move layer state.</p></div></section>}
export function SpecNode({data}){const {config,onChange,caps}=data;const update=(key,v)=>onChange({...config,spec:{...config.spec,[key]:v}});return <section className="graph-node spec-node"><Heading icon={Workflow} title="Speculative decoding" tag="MTP"/>{port('source','spec')}<div className="node-form nodrag"><label className="field">Draft mode<select value={config.spec.mode} onChange={e=>update('mode',e.target.value)}><option value="none">Disabled</option><option disabled={!caps?.flags?.includes('--spec-type')} value="draft-mtp">Built-in / external MTP</option><option disabled={!caps?.flags?.includes('--spec-type')} value="draft-simple">Draft model</option></select></label><label className="field">Draft model path<input required={config.spec.mode==='draft-simple'} disabled={config.spec.mode==='none'} value={config.spec.model_path} placeholder="/path/to/draft.gguf" onChange={e=>update('model_path',e.target.value)}/></label><div className="form-grid"><NumberField label="Draft tokens" min={1} value={config.spec.tokens} onChange={v=>update('tokens',v)}/><NumberField label="Minimum probability" max={1} step={0.05} value={config.spec.p_min} onChange={v=>update('p_min',v)}/></div><label className="field">Draft device<select value={config.spec.device} onChange={e=>update('device',e.target.value)}>{(caps?.devices||[]).map(d=><option disabled={d.available===false||(!!d.alias_of&&d.id!=='MMAP')||d.supported===false} key={d.id} value={d.id}>{d.id}</option>)}</select></label><NumberField label="Draft overhead / MiB" value={config.spec.overhead_mib} onChange={v=>update('overhead_mib',v)}/><p className="hint">Leave empty for built-in MTP in the loaded model. Draft model mode requires a separate GGUF. Support and memory uncertainty are validated by the engine.</p></div></section>}
export function ServerNode({data}){const {config,onChange,runtime,plan}=data;return <section className="graph-node server-node"><Heading icon={Server} title="llama-server" tag={runtime?.running?'RUNNING':'STOPPED'}/>{port('target','server')}<div className="node-form nodrag"><label className="field">Bind address<input value={config.server.host} onChange={e=>onChange({...config,server:{...config.server,host:e.target.value}})}/></label><NumberField label="Server port" min={1024} max={65535} value={config.server.port} onChange={v=>onChange({...config,server:{...config.server,port:v}})}/><Toggle label="Allow network access · expose the managed server" value={config.server.allow_network} onChange={v=>onChange({...config,server:{...config.server,allow_network:v}})}/><p className="hint">127.0.0.1 is local only. 0.0.0.0 exposes llama-server on all IPv4 interfaces; use firewall and authentication. The control plane stays local.</p><Toggle label="Disable CUDA graphs" value={config.environment.cuda_disable_graphs} onChange={v=>onChange({...config,environment:{...config.environment,cuda_disable_graphs:v}})}/><p className="hint">GGML_CUDA_DISABLE_GRAPHS · child process only; no effect on Vulkan.</p><Toggle label="I accept an unknown memory estimate" value={config.acknowledge_estimate} onChange={v=>onChange({...config,acknowledge_estimate:v})}/><p className="hint">Not a safety guarantee. This cannot override validation errors or an OOM budget. Monitor memory during launch.</p><div className="server-state"><i className={'dot '+(runtime?.running?'online':'')}/>{runtime?.running?runtime.health||'Starting':plan?.launchable?'Validated · ready to start':'Waiting for a valid plan'}</div><p className="hint">Connect model, context, and optional draft outputs. Start and stop from the command bar.</p></div></section>}
const nodeTypes={model:ModelNode,device:DeviceNode,context:ContextNode,spec:SpecNode,server:ServerNode,split:SplitNode,sampling:SamplingNode,vision:VisionNode};
export default function Graph(input){const props={...input,config:hydrateConfig(input.config)};const {config,model,caps,plan,onChange,onAssign,onError}=props;const devices=caps?.devices||[];const [livePositions,setLivePositions]=useState({});const [flow,setFlow]=useState(null);const [measurements,setMeasurements]=useState({});
 const nodes=useMemo(()=>{const all=[{id:'model',type:'model',position:{x:60,y:90}},{id:'context',type:'context',position:{x:60,y:790}},{id:'split',type:'split',position:{x:470,y:90}},{id:'sampling',type:'sampling',position:{x:820,y:90}},{id:'spec',type:'spec',position:{x:470,y:790}},{id:'vision',type:'vision',position:{x:820,y:790}},{id:'server',type:'server',position:{x:1170,y:90}},...devices.map((d,i)=>({id:'device:'+d.id,type:'device',position:{x:1170+(i%2)*370,y:790+Math.floor(i/2)*370},device:d}))];return all.map(n=>({...n,measured:measurements[n.id],position:livePositions[n.id]||config.positions?.[n.id]||n.position,data:{...props,device:n.device,memory:plan?.memory?.find(m=>m.id===n.device?.id)}}))},[props,livePositions,measurements]);
 const edges=useMemo(()=>[...(config.edges||[]).filter(e=>e.source!=='model'||e.sourceHandle==='model-out'||e.target==='server'),...Object.entries(config.placement_mode==='layer'?{}:config.placements||{}).filter(([g,d])=>model?.groups?.some(x=>x.id===g)&&devices.some(x=>x.id===d)).map(([g,d])=>({id:'allocation:'+g,source:'model',sourceHandle:g,target:'device:'+d,targetHandle:'allocation',style:{stroke:d.toUpperCase().includes('CUDA')?'#58cad4':d.toUpperCase().includes('VULKAN')?'#b9a1e5':'#91be94',strokeWidth:1.2,opacity:.55}}))],[config,model,devices]);
 const connect=e=>{if(e.source==='model'&&e.sourceHandle!=='model-out'&&e.target.startsWith('device:')){const d=devices.find(d=>'device:'+d.id===e.target);if(config.placement_mode==='layer'){onError('Switch to Manual tensor graph before assigning groups.');return}if(d&&d.available!==false&&d.supported!==false&&( !d.alias_of||d.id==='MMAP')&&config.devices?.[d.id]?.enabled!==false)onAssign([e.sourceHandle],d.id);else onError('This device has no available verified allocation route.')}else{try{onChange(connectGraph(config,e))}catch(err){onError(err.message)}}};
 return <div className="graph-canvas"><div className="canvas-caption"><span className="dot online"/>LIVE TOPOLOGY <span> / {model?'GGUF tensor map':'Awaiting model'}</span></div><nav className="graph-jump" aria-label="Focus graph node">{['model','split','context','sampling','spec','vision','server'].map(id=><button key={id} aria-label={'Focus '+id} onClick={()=>flow?.fitView({nodes:[{id}],padding:.3,maxZoom:1,duration:0})}>{id==='spec'?'MTP / draft':id}</button>)}<button onClick={()=>flow?.fitView({padding:.12,maxZoom:.85})}>Overview</button></nav><ReactFlow onInit={setFlow} nodes={nodes} edges={edges} nodeTypes={nodeTypes} onConnect={connect} onNodesChange={changes=>{if(changes.some(c=>c.type==='dimensions'))setMeasurements(p=>{let next=p;for(const c of changes)if(c.type==='dimensions'&&c.dimensions&&(p[c.id]?.width!==c.dimensions.width||p[c.id]?.height!==c.dimensions.height))next={...next,[c.id]:c.dimensions};return next});if(changes.some(c=>c.type==='position'))setLivePositions(p=>{const next={...p};for(const c of changes)if(c.type==='position'&&c.position)next[c.id]=c.position;return next})}} onNodeDragStop={(_,node)=>onChange({...config,positions:{...config.positions,...livePositions,[node.id]:node.position}})} onEdgesDelete={deleted=>{const ids=new Set(deleted.map(e=>e.id));const placements={...config.placements};const removed=deleted.filter(e=>e.id.startsWith('allocation:')).map(e=>e.sourceHandle);removed.forEach(id=>delete placements[id]);onChange({...config,placements,locked:config.locked.filter(id=>!removed.includes(id)),edges:(config.edges||[]).filter(e=>!ids.has(e.id)),spec:deleted.some(e=>e.source==='spec')?{...config.spec,mode:'none'}:config.spec})}} fitView fitViewOptions={{padding:.12,maxZoom:.85}} minZoom={.25} maxZoom={1.5} colorMode="dark" deleteKeyCode={['Backspace','Delete']} proOptions={{hideAttribution:true}}><Background color="#34373b" gap={22} size={1}/><Controls showInteractive={false}/><MiniMap pannable zoomable nodeColor={n=>n.type==='device'?'#6d8994':n.type==='model'?'#ba9147':'#565e69'} maskColor="rgba(17,19,22,.75)"/></ReactFlow></div>
}
